### ISSUE TITLE
occasional SIGSEGV on exit

### ISSUE THREAD

**Issue by sorokin** [eteran/edb-debugger#652]
From time to time I keep getting this SIGSEGV when edb is exiting. The bug is not reproducible deterministically, but I see it quite often on my setup. I use Qt 5.9.1.

```
Terminal process has TTY:  "/dev/pts/7"
Loading session file
Loading plugin-data
restoreComments
[Thread 0x7fffcb3cd700 (LWP 14390) exited]
Saving session file
[Thread 0x7fffcdf00700 (LWP 14388) exited]
[Thread 0x7fffdf4b1700 (LWP 14385) exited]
[Thread 0x7fffd6e0c700 (LWP 14386) exited]
[Thread 0x7fffcc331700 (LWP 14389) exited]

Thread 1 "edb" received signal SIGSEGV, Segmentation fault.
0x00007ffff5e6ba4f in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
(gdb) bt
#0  0x00007ffff5e6ba4f in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
#1  0x00007ffff5e1b9bc in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
#2  0x00007ffff5e1c349 in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
#3  0x00007ffff501a2c7 in QObject::~QObject() () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#4  0x00007ffff5e16d8a in QNetworkAccessManager::~QNetworkAccessManager() () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
#5  0x00007ffff5e16dd9 in QNetworkAccessManager::~QNetworkAccessManager() () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Network.so.5
#6  0x00007ffff5010431 in QObjectPrivate::deleteChildren() () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#7  0x00007ffff501a27f in QObject::~QObject() () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#8  0x00007fffd22020c5 in CheckVersionPlugin::CheckVersion::~CheckVersion (this=0x60400006bc90, __in_chrg=<optimized out>)
    at /home/ivan/d/edb-debugger/plugins/CheckVersion/CheckVersion.cpp:47
#9  0x00007fffd2202114 in CheckVersionPlugin::CheckVersion::~CheckVersion (this=0x60400006bc90, __in_chrg=<optimized out>)
    at /home/ivan/d/edb-debugger/plugins/CheckVersion/CheckVersion.cpp:48
#10 0x00007ffff4fdc839 in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#11 0x00007ffff4fddebf in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#12 0x00007ffff344334f in __cxa_finalize () from /nix/store/c6jkgsydcd93l5lj3rqib5r64bqpc93x-glibc-2.25-123/lib/libc.so.6
#13 0x00007ffff4debc93 in ?? () from /nix/store/8g9dj47lgnzwp53y6bdja1prcw75p21n-qtbase-5.9.1/lib/libQt5Core.so.5
#14 0x00007fffffffc470 in ?? ()
#15 0x00007ffff7de97b7 in _dl_fini () from /nix/store/c6jkgsydcd93l5lj3rqib5r64bqpc93x-glibc-2.25-123/lib/ld-linux-x86-64.so.2
Backtrace stopped: frame did not save the PC
```

Sorry for missing symbols for Qt library. From what I understand __cxa_finalize is called when destructors for global variables need to be run. In the destructor for some global variable in Qt5Core an object of class CheckVersion is deleted. The destructor of it tries to delete its child QNetworkAccessManager.

As far as I know (but I'm not 100% sure) in Qt it is forbidden to access any Qt classes after QApplication is destroyed and we obviously are past the point when QApplication is destroyed as we exited main already.

I'm not familiar with how Qt plugins work. So for now I'm going to just leave the report here. Unless somebody looks at it, I'm going to look at it later. At least I need to read about Qt Plugins and I need to compile Qt with debug information.

**Comment by eteran** [comment]
Right, I've been aware of a crash caused by CheckVersion occasionally, but have never been able to reproduce it reliably. I **think** it occurs when the HTTP request is still outstanding when edb is shut down.

**Comment by eteran** [comment]
Seems related to this: https://bugreports.qt.io/browse/QTBUG-21406

**Comment by 10110111** [comment]
Are you sure it's related? That bug has been fixed long ago (in 2011) in Qt 4.7.x. I reproduce CheckVersion's crash with Qt 5.5.1 with current master EDB.

**Comment by eteran** [comment]
Not 100% sure, but looking at the code we have, I don't see anything we should be doing differently 😕

**Comment by sorokin** [comment]
FYI, this bug happened to me today on the latest master.
