### ISSUE TITLE
memory leak in ODBRegView::modelReset

### ISSUE THREAD

**Issue by sorokin** [eteran/edb-debugger#745]
Leak sanitizer reports this leak:

```
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fa9f4872d80 in operator new(unsigned long) (/nix/store/784rh7jrfhagbkydjfrv68h9x3g4gqmk-gcc-8.3.0-lib/lib/libasan.so.5+0xedd80)
    #1 0x7fa9dccdce6c in ODbgRegisterView::ODBRegView::modelReset() /home/ivan/d/edb-debugger/plugins/ODbgRegisterView/RegisterView.cpp:461
```

Line 461 is:
```
	const auto flagsAndSegments = new QHBoxLayout();
```

Apparently QHBoxLayout is created without a parent.

**Comment by eteran** [comment]
I **think** this should be fixed in master. Please double check when you get a chance and re-open the issue as needed.

Thanks!
